### ISSUE TITLE
Why asking for (n_agents*n_exp) API keys? 

### ISSUE THREAD

**Issue by federicoceli** [WestlakeIntelligentRobotics/ConsensusLLM-code#7]
What is the idea behind the following condition in ```vector2d_debate.py``` ?

```python 
if len(api_keys) < self._n_agents * args.n_exp:
            raise ValueError("api_keys are not enough for "
                             f"{self._n_agents} agents")
```

Why are we asking for so many keys? Is using one key enough (or at most one per agent, regardless of the number of experiments)?

**Comment by jwk1rose** [comment]
Sorry for the late response. In order to expedite the progress of the experiment, we ran numerous threads concurrently to experiment simultaneously.

**Comment by huabench** [comment]
The issue has been resolved, and I will close it now. Feel free to raise any other concerns.
